### ISSUE TITLE
Kontakformular - Funktion

### ISSUE THREAD

**Issue by Simi2394** [Gitimur/timzuercher#10]
**DoR**
- [x] [Issue](https://github.com/Gitimur/timzuercher/issues/10#issue-1477086581) erstellen
- [x] Kontaktformular auf Funktion prüfen
- [x] Funktion des Kontaktformulars einbinden
- [x] Code Review
- [x] Kommentar hinzufügen
- [x] Pull Requests ([1](https://github.com/Gitimur/timzuercher/pull/12), [2,](https://github.com/Gitimur/timzuercher/pull/13) [3)](https://github.com/Gitimur/timzuercher/pull/14) erstellen 

**DoD**

- [x] Check ob Issue im [GitHub Repo](https://github.com/Gitimur/timzuercher) geschlossen wurde
- [x] Check ob Pull Request im [GitHub Repo](https://github.com/Gitimur/timzuercher) ready for merge ist
- [x] Check ob Pull Request in [GitHub Repo](https://github.com/Gitimur/timzuercher) gemerged wurde

**Comment by Gitimur** [comment]
thx simi2394
